export type WordCard = {
  word: string;
  pronunciation: string;
  meaning: string;
};

export const WORDS: WordCard[] = [
  { word: "привет", pronunciation: "pree-VYET", meaning: "hello (informal)" },
  { word: "здравствуйте", pronunciation: "ZDRA-stvooy-tyeh", meaning: "hello (formal)" },
  { word: "доброе утро", pronunciation: "DOH-brah-yeh OO-trah", meaning: "good morning" },
  { word: "добрый день", pronunciation: "DOH-briy DYEN'", meaning: "good afternoon" },
  { word: "добрый вечер", pronunciation: "DOH-briy VYE-cher", meaning: "good evening" },
  { word: "спокойной ночи", pronunciation: "spah-KOY-noy NOH-chee", meaning: "good night" },
  { word: "пока", pronunciation: "pah-KAH", meaning: "bye" },
  { word: "до свидания", pronunciation: "dah svee-DAH-nee-yah", meaning: "goodbye" },
  { word: "увидимся", pronunciation: "oo-VEE-deem-syah", meaning: "see you" },
  { word: "как дела", pronunciation: "kahk dee-LAH", meaning: "how are things?" },
  { word: "хорошо", pronunciation: "khah-rah-SHOH", meaning: "good / fine" },
  { word: "нормально", pronunciation: "nar-MAHL'-nah", meaning: "okay / normal" },
  { word: "плохо", pronunciation: "PLOH-khah", meaning: "bad" },
  { word: "отлично", pronunciation: "at-LEECH-nah", meaning: "excellent" },
  { word: "спасибо", pronunciation: "spah-SEE-bah", meaning: "thank you" },
  { word: "пожалуйста", pronunciation: "pah-ZHAH-loo-stah", meaning: "please / you're welcome" },
  { word: "извините", pronunciation: "eez-vee-NEE-tyeh", meaning: "excuse me / sorry (formal)" },
  { word: "прости", pronunciation: "prah-STEE", meaning: "sorry (informal)" },
  { word: "не за что", pronunciation: "neh zah SHTOH", meaning: "don't mention it" },
  { word: "да", pronunciation: "dah", meaning: "yes" },
  { word: "нет", pronunciation: "nyet", meaning: "no" },
  { word: "может быть", pronunciation: "MOH-zhet byt'", meaning: "maybe" },
  { word: "конечно", pronunciation: "kah-NEHCH-nah", meaning: "of course" },
  { word: "пожалуй", pronunciation: "pah-ZHAH-looy", meaning: "probably / I guess" },
  { word: "хорошо", pronunciation: "khah-rah-SHOH", meaning: "okay" },
  { word: "ладно", pronunciation: "LAHD-nah", meaning: "alright" },
  { word: "окей", pronunciation: "oh-KAY", meaning: "okay (loanword)" },
  { word: "я", pronunciation: "yah", meaning: "I" },
  { word: "ты", pronunciation: "ty", meaning: "you (singular informal)" },
  { word: "вы", pronunciation: "vy", meaning: "you (plural / formal)" },
  { word: "он", pronunciation: "ohn", meaning: "he" },
  { word: "она", pronunciation: "ah-NAH", meaning: "she" },
  { word: "оно", pronunciation: "ah-NOH", meaning: "it" },
  { word: "мы", pronunciation: "my", meaning: "we" },
  { word: "они", pronunciation: "ah-NEE", meaning: "they" },
  { word: "мой", pronunciation: "moy", meaning: "my" },
  { word: "твой", pronunciation: "tvoy", meaning: "your (informal)" },
  { word: "ваш", pronunciation: "vahsh", meaning: "your (formal/plural)" },
  { word: "его", pronunciation: "yeh-VOH", meaning: "his" },
  { word: "её", pronunciation: "yeh-YOH", meaning: "her" },
  { word: "их", pronunciation: "eekh", meaning: "their" },
  { word: "кто", pronunciation: "ktoh", meaning: "who" },
  { word: "что", pronunciation: "shtoh", meaning: "what" },
  { word: "где", pronunciation: "gdyeh", meaning: "where" },
  { word: "куда", pronunciation: "koo-DAH", meaning: "where to" },
  { word: "откуда", pronunciation: "at-koo-DAH", meaning: "where from" },
  { word: "когда", pronunciation: "kahg-DAH", meaning: "when" },
  { word: "почему", pronunciation: "pah-chee-MOO", meaning: "why" },
  { word: "зачем", pronunciation: "zah-CHYEM", meaning: "what for / why" },
  { word: "как", pronunciation: "kahk", meaning: "how" },
  { word: "какой", pronunciation: "kah-KOY", meaning: "which / what kind" },
  { word: "какая", pronunciation: "kah-KAH-yah", meaning: "which (fem.)" },
  { word: "какое", pronunciation: "kah-KOH-yeh", meaning: "which (neut.)" },
  { word: "какие", pronunciation: "kah-KEE-yeh", meaning: "which (plural)" },
  { word: "этот", pronunciation: "EH-tat", meaning: "this (masc.)" },
  { word: "эта", pronunciation: "EH-tah", meaning: "this (fem.)" },
  { word: "это", pronunciation: "EH-tah", meaning: "this/that (neut.) / it is" },
  { word: "эти", pronunciation: "EH-tee", meaning: "these" },
  { word: "тот", pronunciation: "toht", meaning: "that (masc.)" },
  { word: "та", pronunciation: "tah", meaning: "that (fem.)" },
  { word: "то", pronunciation: "toh", meaning: "that (neut.)" },
  { word: "те", pronunciation: "tyeh", meaning: "those" },
  { word: "здесь", pronunciation: "zdes'", meaning: "here" },
  { word: "там", pronunciation: "tahm", meaning: "there" },
  { word: "тут", pronunciation: "toot", meaning: "here (colloquial)" },
  { word: "сейчас", pronunciation: "see-CHAS", meaning: "now" },
  { word: "сегодня", pronunciation: "see-VOHD-nyah", meaning: "today" },
  { word: "вчера", pronunciation: "vchee-RAH", meaning: "yesterday" },
  { word: "завтра", pronunciation: "ZAHF-trah", meaning: "tomorrow" },
  { word: "рано", pronunciation: "RAH-nah", meaning: "early" },
  { word: "поздно", pronunciation: "POHZ-dnah", meaning: "late" },
  { word: "быстро", pronunciation: "BYS-trah", meaning: "fast" },
  { word: "медленно", pronunciation: "MYED-lehn-nah", meaning: "slowly" },
  { word: "снова", pronunciation: "SNOH-vah", meaning: "again" },
  { word: "ещё", pronunciation: "ye-SHCHYO", meaning: "still / more" },
  { word: "уже", pronunciation: "oo-ZHEH", meaning: "already" },
  { word: "только", pronunciation: "TOHL'-kah", meaning: "only / just" },
  { word: "всегда", pronunciation: "fseeg-DAH", meaning: "always" },
  { word: "никогда", pronunciation: "nee-kahg-DAH", meaning: "never" },
  { word: "иногда", pronunciation: "een-ahg-DAH", meaning: "sometimes" },
  { word: "часто", pronunciation: "CHAS-tah", meaning: "often" },
  { word: "редко", pronunciation: "RYED-kah", meaning: "rarely" },
  { word: "один", pronunciation: "ah-DEEN", meaning: "one" },
  { word: "два", pronunciation: "dvah", meaning: "two" },
  { word: "три", pronunciation: "tree", meaning: "three" },
  { word: "четыре", pronunciation: "chee-TYH-ree", meaning: "four" },
  { word: "пять", pronunciation: "pyat'", meaning: "five" },
  { word: "шесть", pronunciation: "shest'", meaning: "six" },
  { word: "семь", pronunciation: "syem'", meaning: "seven" },
  { word: "восемь", pronunciation: "VOH-seem'", meaning: "eight" },
  { word: "девять", pronunciation: "DYEH-vyat'", meaning: "nine" },
  { word: "десять", pronunciation: "DYEH-syat'", meaning: "ten" },
  { word: "одиннадцать", pronunciation: "ah-DEE-nah-tsat'", meaning: "eleven" },
  { word: "двенадцать", pronunciation: "dvee-NAH-tsat'", meaning: "twelve" },
  { word: "тринадцать", pronunciation: "tree-NAH-tsat'", meaning: "thirteen" },
  { word: "четырнадцать", pronunciation: "chee-TYHR-nah-tsat'", meaning: "fourteen" },
  { word: "пятнадцать", pronunciation: "peet-NAH-tsat'", meaning: "fifteen" },
  { word: "шестнадцать", pronunciation: "shest-NAH-tsat'", meaning: "sixteen" },
  { word: "семнадцать", pronunciation: "seem-NAH-tsat'", meaning: "seventeen" },
  { word: "восемнадцать", pronunciation: "vah-seem-NAH-tsat'", meaning: "eighteen" },
  { word: "девятнадцать", pronunciation: "dee-vyeet-NAH-tsat'", meaning: "nineteen" },
  { word: "двадцать", pronunciation: "DVAH-tsat'", meaning: "twenty" },
  { word: "тридцать", pronunciation: "TREE-tsat'", meaning: "thirty" },
  { word: "сорок", pronunciation: "SOH-rak", meaning: "forty" },
  { word: "пятьдесят", pronunciation: "peet-dee-SYAT", meaning: "fifty" },
  { word: "шестьдесят", pronunciation: "shest-dee-SYAT", meaning: "sixty" },
  { word: "семьдесят", pronunciation: "seem-dee-SYAT", meaning: "seventy" },
  { word: "восемьдесят", pronunciation: "VOH-seem'-dee-syat", meaning: "eighty" },
  { word: "девяносто", pronunciation: "dee-vya-NOH-stah", meaning: "ninety" },
  { word: "сто", pronunciation: "stoh", meaning: "one hundred" },
  { word: "тысяча", pronunciation: "TYH-syah-chah", meaning: "one thousand" },
  { word: "понедельник", pronunciation: "pah-nee-DYEHL'-neek", meaning: "Monday" },
  { word: "вторник", pronunciation: "VTOR-neek", meaning: "Tuesday" },
  { word: "среда", pronunciation: "sree-DAH", meaning: "Wednesday" },
  { word: "четверг", pronunciation: "chee-TVEHRK", meaning: "Thursday" },
  { word: "пятница", pronunciation: "PYAT-nee-tsah", meaning: "Friday" },
  { word: "суббота", pronunciation: "soo-BOH-tah", meaning: "Saturday" },
  { word: "воскресенье", pronunciation: "vah-skah-ree-SYEHN'-yeh", meaning: "Sunday" },
  { word: "январь", pronunciation: "yeen-VAHR'", meaning: "January" },
  { word: "февраль", pronunciation: "feev-RAL'", meaning: "February" },
  { word: "март", pronunciation: "mahrt", meaning: "March" },
  { word: "апрель", pronunciation: "ah-PREHL'", meaning: "April" },
  { word: "май", pronunciation: "my", meaning: "May" },
  { word: "июнь", pronunciation: "ee-YOON'", meaning: "June" },
  { word: "июль", pronunciation: "ee-YOOL'", meaning: "July" },
  { word: "август", pronunciation: "AH-voost", meaning: "August" },
  { word: "сентябрь", pronunciation: "seen-TYAHB-r'", meaning: "September" },
  { word: "октябрь", pronunciation: "ak-TYAHB-r'", meaning: "October" },
  { word: "ноябрь", pronunciation: "nah-YAHB-r'", meaning: "November" },
  { word: "декабрь", pronunciation: "dee-KAHB-r'", meaning: "December" },
  { word: "чёрный", pronunciation: "CHYOR-niy", meaning: "black" },
  { word: "белый", pronunciation: "BYEH-liy", meaning: "white" },
  { word: "красный", pronunciation: "KRAS-niy", meaning: "red" },
  { word: "синий", pronunciation: "SEE-neey", meaning: "blue (dark)" },
  { word: "голубой", pronunciation: "gah-loo-BOY", meaning: "blue (light)" },
  { word: "зелёный", pronunciation: "zee-LYOH-niy", meaning: "green" },
  { word: "жёлтый", pronunciation: "ZHYOL-tiy", meaning: "yellow" },
  { word: "серый", pronunciation: "SYEH-riy", meaning: "gray" },
  { word: "коричневый", pronunciation: "kah-RECH-nee-vee", meaning: "brown" },
  { word: "розовый", pronunciation: "ROH-zah-viy", meaning: "pink" },
  { word: "оранжевый", pronunciation: "ah-RAN-zheh-viy", meaning: "orange" },
  { word: "фиолетовый", pronunciation: "fee-ah-LYEH-tah-viy", meaning: "purple" },
  { word: "мама", pronunciation: "MAH-mah", meaning: "mom" },
  { word: "папа", pronunciation: "PAH-pah", meaning: "dad" },
  { word: "родители", pronunciation: "rah-DEE-tee-lee", meaning: "parents" },
  { word: "сын", pronunciation: "syn", meaning: "son" },
  { word: "дочь", pronunciation: "doch'", meaning: "daughter" },
  { word: "брат", pronunciation: "braht", meaning: "brother" },
  { word: "сестра", pronunciation: "sees-TRA", meaning: "sister" },
  { word: "муж", pronunciation: "moozh", meaning: "husband" },
  { word: "жена", pronunciation: "zhye-NAH", meaning: "wife" },
  { word: "ребёнок", pronunciation: "ree-BYOH-nak", meaning: "child" },
  { word: "дети", pronunciation: "DYEH-tee", meaning: "children" },
  { word: "семья", pronunciation: "seem-YAH", meaning: "family" },
  { word: "друг", pronunciation: "droog", meaning: "friend (male)" },
  { word: "подруга", pronunciation: "pah-DOO-gah", meaning: "friend (female)" },
  { word: "парень", pronunciation: "PAH-reen'", meaning: "guy / boyfriend" },
  { word: "девушка", pronunciation: "DYEH-voosh-kah", meaning: "girl / girlfriend" },
  { word: "мужчина", pronunciation: "moo-SHEE-nah", meaning: "man" },
  { word: "женщина", pronunciation: "ZHEHN-shee-nah", meaning: "woman" },
  { word: "человек", pronunciation: "chee-lah-VYEHK", meaning: "person / human" },
  { word: "люди", pronunciation: "LYOO-dee", meaning: "people" },
  { word: "имя", pronunciation: "EE-myah", meaning: "name" },
  { word: "фамилия", pronunciation: "fah-MEE-lee-yah", meaning: "last name" },
  { word: "возраст", pronunciation: "VOHZ-rast", meaning: "age" },
  { word: "дом", pronunciation: "dohm", meaning: "house / home" },
  { word: "квартира", pronunciation: "kvahr-TEE-rah", meaning: "apartment" },
  { word: "комната", pronunciation: "kahm-NAH-tah", meaning: "room" },
  { word: "кухня", pronunciation: "KOOH-nyah", meaning: "kitchen" },
  { word: "ванная", pronunciation: "VAHN-nah-yah", meaning: "bathroom (with bath)" },
  { word: "туалет", pronunciation: "too-ah-LYEHT", meaning: "toilet" },
  { word: "дверь", pronunciation: "dvyer'", meaning: "door" },
  { word: "окно", pronunciation: "ak-NOH", meaning: "window" },
  { word: "стена", pronunciation: "stee-NAH", meaning: "wall" },
  { word: "пол", pronunciation: "pohl", meaning: "floor" },
  { word: "потолок", pronunciation: "pah-tah-LOHK", meaning: "ceiling" },
  { word: "стол", pronunciation: "stohl", meaning: "table" },
  { word: "стул", pronunciation: "stool", meaning: "chair" },
  { word: "кровать", pronunciation: "krah-VAT'", meaning: "bed" },
  { word: "диван", pronunciation: "dee-VAHN", meaning: "sofa" },
  { word: "шкаф", pronunciation: "shkahf", meaning: "wardrobe / cabinet" },
  { word: "зеркало", pronunciation: "ZEHR-kah-lah", meaning: "mirror" },
  { word: "лампа", pronunciation: "LAHM-pah", meaning: "lamp" },
  { word: "свет", pronunciation: "svyet", meaning: "light" },
  { word: "ключ", pronunciation: "klyooch", meaning: "key" },
  { word: "телефон", pronunciation: "tee-lee-FOHN", meaning: "phone" },
  { word: "компьютер", pronunciation: "kahm-PYOO-ter", meaning: "computer" },
  { word: "интернет", pronunciation: "een-ter-NYEHT", meaning: "internet" },
  { word: "книга", pronunciation: "KNEE-gah", meaning: "book" },
  { word: "тетрадь", pronunciation: "tee-TRAT'", meaning: "notebook" },
  { word: "ручка", pronunciation: "ROOCH-kah", meaning: "pen" },
  { word: "карандаш", pronunciation: "kah-rahn-DASH", meaning: "pencil" },
  { word: "бумага", pronunciation: "boo-MAH-gah", meaning: "paper" },
  { word: "сумка", pronunciation: "SOOM-kah", meaning: "bag" },
  { word: "рюкзак", pronunciation: "ryook-ZAK", meaning: "backpack" },
  { word: "одежда", pronunciation: "ah-DYEZH-dah", meaning: "clothes" },
  { word: "футболка", pronunciation: "foot-BOL-kah", meaning: "t-shirt" },
  { word: "рубашка", pronunciation: "roo-BASH-kah", meaning: "shirt" },
  { word: "свитер", pronunciation: "SVEE-ter", meaning: "sweater" },
  { word: "куртка", pronunciation: "KOORT-kah", meaning: "jacket" },
  { word: "пальто", pronunciation: "pahl-TOH", meaning: "coat" },
  { word: "джинсы", pronunciation: "JEEN-sy", meaning: "jeans" },
  { word: "брюки", pronunciation: "bryoo-KEE", meaning: "pants / trousers" },
  { word: "платье", pronunciation: "PLAT'-yeh", meaning: "dress" },
  { word: "юбка", pronunciation: "YOOB-kah", meaning: "skirt" },
  { word: "обувь", pronunciation: "OH-boof'", meaning: "footwear" },
  { word: "ботинки", pronunciation: "bah-TEEN-kee", meaning: "boots" },
  { word: "кроссовки", pronunciation: "krah-SOF-kee", meaning: "sneakers" },
  { word: "носок", pronunciation: "nah-SOHK", meaning: "sock" },
  { word: "шапка", pronunciation: "SHAHP-kah", meaning: "hat" },
  { word: "шарф", pronunciation: "shahrf", meaning: "scarf" },
  { word: "перчатки", pronunciation: "peer-CHAT-kee", meaning: "gloves" },
  { word: "вода", pronunciation: "vah-DAH", meaning: "water" },
  { word: "чай", pronunciation: "chy", meaning: "tea" },
  { word: "кофе", pronunciation: "KOH-feh", meaning: "coffee" },
  { word: "молоко", pronunciation: "mah-lah-KOH", meaning: "milk" },
  { word: "сок", pronunciation: "sohk", meaning: "juice" },
  { word: "пиво", pronunciation: "PEE-vah", meaning: "beer" },
  { word: "вино", pronunciation: "vee-NOH", meaning: "wine" },
  { word: "хлеб", pronunciation: "khlyehb", meaning: "bread" },
  { word: "сыр", pronunciation: "syr", meaning: "cheese" },
  { word: "масло", pronunciation: "MAHS-lah", meaning: "butter / oil" },
  { word: "яйцо", pronunciation: "yah-YTSOH", meaning: "egg" },
  { word: "мясо", pronunciation: "MYAH-sah", meaning: "meat" },
  { word: "рыба", pronunciation: "RYE-bah", meaning: "fish" },
  { word: "курица", pronunciation: "KOO-ree-tsah", meaning: "chicken" },
  { word: "суп", pronunciation: "soop", meaning: "soup" },
  { word: "салат", pronunciation: "sah-LAHT", meaning: "salad" },
  { word: "рис", pronunciation: "rees", meaning: "rice" },
  { word: "макароны", pronunciation: "mah-kah-ROH-ny", meaning: "pasta" },
  { word: "картошка", pronunciation: "kahr-TOSH-kah", meaning: "potato (colloquial)" },
  { word: "картофель", pronunciation: "kahr-TOH-fehl'", meaning: "potato (formal)" },
  { word: "помидор", pronunciation: "pah-mee-DOR", meaning: "tomato" },
  { word: "огурец", pronunciation: "ah-goo-RYEHTS", meaning: "cucumber" },
  { word: "лук", pronunciation: "look", meaning: "onion" },
  { word: "чеснок", pronunciation: "chee-SNOHK", meaning: "garlic" },
  { word: "морковь", pronunciation: "mahr-KOF'", meaning: "carrot" },
  { word: "яблоко", pronunciation: "YA-blah-kah", meaning: "apple" },
  { word: "банан", pronunciation: "bah-NAHN", meaning: "banana" },
  { word: "апельсин", pronunciation: "ah-peel'-SEEN", meaning: "orange (fruit)" },
  { word: "лимон", pronunciation: "lee-MOHN", meaning: "lemon" },
  { word: "клубника", pronunciation: "kloob-NEE-kah", meaning: "strawberry" },
  { word: "сахар", pronunciation: "SAH-khar", meaning: "sugar" },
  { word: "соль", pronunciation: "sohl'", meaning: "salt" },
  { word: "перец", pronunciation: "PYEH-rets", meaning: "pepper" },
  { word: "вкусно", pronunciation: "VKOOS-nah", meaning: "tasty" },
  { word: "голодный", pronunciation: "GAH-lad-niy", meaning: "hungry (male)" },
  { word: "голодная", pronunciation: "GAH-lad-nah-yah", meaning: "hungry (female)" },
  { word: "сыт", pronunciation: "syt", meaning: "full (not hungry) (male)" },
  { word: "сыта", pronunciation: "SY-tah", meaning: "full (female)" },
  { word: "город", pronunciation: "GOH-raht", meaning: "city" },
  { word: "улица", pronunciation: "OO-lee-tsah", meaning: "street" },
  { word: "площадь", pronunciation: "PLOH-shchad'", meaning: "square (plaza)" },
  { word: "дорога", pronunciation: "dah-ROH-gah", meaning: "road" },
  { word: "мост", pronunciation: "most", meaning: "bridge" },
  { word: "река", pronunciation: "ree-KAH", meaning: "river" },
  { word: "озеро", pronunciation: "OH-zeh-rah", meaning: "lake" },
  { word: "море", pronunciation: "MOH-ryeh", meaning: "sea" },
  { word: "гора", pronunciation: "gah-RAH", meaning: "mountain" },
  { word: "лес", pronunciation: "lyes", meaning: "forest" },
  { word: "парк", pronunciation: "pahrk", meaning: "park" },
  { word: "сад", pronunciation: "saht", meaning: "garden" },
  { word: "дерево", pronunciation: "dyeh-REH-vah", meaning: "tree" },
  { word: "цветок", pronunciation: "tsvee-TOHK", meaning: "flower" },
  { word: "трава", pronunciation: "trah-VAH", meaning: "grass" },
  { word: "снег", pronunciation: "snyek", meaning: "snow" },
  { word: "дождь", pronunciation: "doshch", meaning: "rain" },
  { word: "ветер", pronunciation: "VYEH-ter", meaning: "wind" },
  { word: "солнце", pronunciation: "SOHN-tseh", meaning: "sun" },
  { word: "небо", pronunciation: "NYEH-bah", meaning: "sky" },
  { word: "звезда", pronunciation: "zvyez-DAH", meaning: "star" },
  { word: "луна", pronunciation: "loo-NAH", meaning: "moon" },
  { word: "погода", pronunciation: "pah-GOH-dah", meaning: "weather" },
  { word: "холодно", pronunciation: "KHOH-lad-nah", meaning: "cold" },
  { word: "жарко", pronunciation: "ZHAHR-kah", meaning: "hot" },
  { word: "тепло", pronunciation: "tee-PLoh", meaning: "warm" },
  { word: "прохладно", pronunciation: "prah-KHLAHD-nah", meaning: "cool (weather)" },
  { word: "магазин", pronunciation: "mah-gah-ZEEN", meaning: "shop/store" },
  { word: "рынок", pronunciation: "RYE-nak", meaning: "market" },
  { word: "цена", pronunciation: "tsee-NAH", meaning: "price" },
  { word: "деньги", pronunciation: "DYEHN'-gee", meaning: "money" },
  { word: "карта", pronunciation: "KAHR-tah", meaning: "card / map" },
  { word: "наличные", pronunciation: "nah-LEECH-nee-yeh", meaning: "cash" },
  { word: "чек", pronunciation: "chek", meaning: "receipt/check" },
  { word: "скидка", pronunciation: "SKEET-kah", meaning: "discount" },
  { word: "дорого", pronunciation: "DAH-rah-gah", meaning: "expensive" },
  { word: "дёшево", pronunciation: "DYO-shee-vah", meaning: "cheap" },
  { word: "купить", pronunciation: "koo-PEET'", meaning: "to buy" },
  { word: "продать", pronunciation: "prah-DAT'", meaning: "to sell" },
  { word: "выбрать", pronunciation: "VY-braht'", meaning: "to choose" },
  { word: "искать", pronunciation: "ees-KAT'", meaning: "to search/look for" },
  { word: "найти", pronunciation: "ny-TY", meaning: "to find" },
  { word: "нужный", pronunciation: "NOOZH-niy", meaning: "needed / necessary" },
  { word: "нужно", pronunciation: "NOOZH-nah", meaning: "need / must" },
  { word: "работа", pronunciation: "rah-BOH-tah", meaning: "work (noun)" },
  { word: "работать", pronunciation: "rah-BOH-taht'", meaning: "to work" },
  { word: "учиться", pronunciation: "oo-CHEE-tsah", meaning: "to study / learn" },
  { word: "учитель", pronunciation: "oo-CHEE-tehl'", meaning: "teacher" },
  { word: "студент", pronunciation: "stoo-DYEHNT", meaning: "student (male)" },
  { word: "студентка", pronunciation: "stoo-DYEHNT-kah", meaning: "student (female)" },
  { word: "школа", pronunciation: "SHKOH-lah", meaning: "school" },
  { word: "университет", pronunciation: "oo-nee-veer-see-TYEHT", meaning: "university" },
  { word: "урок", pronunciation: "oo-ROHK", meaning: "lesson" },
  { word: "домашнее задание", pronunciation: "dah-MASH-nee-yeh zah-DAH-nee-yeh", meaning: "homework" },
  { word: "вопрос", pronunciation: "vah-PROHS", meaning: "question" },
  { word: "ответ", pronunciation: "at-VYEHT", meaning: "answer" },
  { word: "ошибка", pronunciation: "ah-SHEEB-kah", meaning: "mistake" },
  { word: "правильно", pronunciation: "PRAH-veel'-nah", meaning: "correctly" },
  { word: "неправильно", pronunciation: "nee-PRAH-veel'-nah", meaning: "incorrectly" },
  { word: "говорить", pronunciation: "gah-vah-REET'", meaning: "to speak" },
  { word: "сказать", pronunciation: "skah-ZAT'", meaning: "to say (once)" },
  { word: "слушать", pronunciation: "SLOO-shaht'", meaning: "to listen" },
  { word: "слышать", pronunciation: "SLY-shaht'", meaning: "to hear" },
  { word: "читать", pronunciation: "chee-TAT'", meaning: "to read" },
  { word: "писать", pronunciation: "pee-SAT'", meaning: "to write" },
  { word: "понимать", pronunciation: "pah-nee-MAT'", meaning: "to understand" },
  { word: "знать", pronunciation: "znat'", meaning: "to know" },
  { word: "учить", pronunciation: "oo-CHEET'", meaning: "to teach / learn (something)" },
  { word: "учить(ся)", pronunciation: "oo-CHEET'(syah)", meaning: "to study (reflexive)" },
  { word: "повторять", pronunciation: "pahf-tah-RYAT'", meaning: "to repeat" },
  { word: "спросить", pronunciation: "sprah-SEET'", meaning: "to ask" },
  { word: "ответить", pronunciation: "at-VYEH-teet'", meaning: "to answer" },
  { word: "идти", pronunciation: "ee-TEE", meaning: "to go (on foot)" },
  { word: "ехать", pronunciation: "YEH-khat'", meaning: "to go (by vehicle)" },
  { word: "приходить", pronunciation: "pree-kha-DEET'", meaning: "to come (habitual)" },
  { word: "прийти", pronunciation: "pree-TY", meaning: "to come (once)" },
  { word: "уходить", pronunciation: "oo-kha-DEET'", meaning: "to leave (habitual)" },
  { word: "уйти", pronunciation: "oo-TY", meaning: "to leave (once)" },
  { word: "ехать", pronunciation: "YEH-khat'", meaning: "to ride/drive/go" },
  { word: "остановка", pronunciation: "ah-stah-NOF-kah", meaning: "stop (bus/tram)" },
  { word: "автобус", pronunciation: "ahv-TOH-boos", meaning: "bus" },
  { word: "трамвай", pronunciation: "trahm-VY", meaning: "tram" },
  { word: "метро", pronunciation: "meh-TROH", meaning: "metro/subway" },
  { word: "поезд", pronunciation: "POH-yeezd", meaning: "train" },
  { word: "станция", pronunciation: "STAHN-tsee-yah", meaning: "station" },
  { word: "аэропорт", pronunciation: "ah-eh-rah-PORT", meaning: "airport" },
  { word: "самолёт", pronunciation: "sah-mah-LYOT", meaning: "airplane" },
  { word: "билет", pronunciation: "bee-LYEHT", meaning: "ticket" },
  { word: "паспорт", pronunciation: "PAHS-port", meaning: "passport" },
  { word: "багаж", pronunciation: "bah-GAHZH", meaning: "luggage" },
  { word: "карта", pronunciation: "KAHR-tah", meaning: "map" },
  { word: "направо", pronunciation: "nah-PRAH-vah", meaning: "to the right" },
  { word: "налево", pronunciation: "nah-LYEH-vah", meaning: "to the left" },
  { word: "прямо", pronunciation: "PRYAH-mah", meaning: "straight ahead" },
  { word: "близко", pronunciation: "BLEEZ-kah", meaning: "near" },
  { word: "далеко", pronunciation: "dah-lee-KOH", meaning: "far" },
  { word: "время", pronunciation: "VRYEH-myah", meaning: "time" },
  { word: "час", pronunciation: "chas", meaning: "hour" },
  { word: "минута", pronunciation: "mee-NOO-tah", meaning: "minute" },
  { word: "секунда", pronunciation: "see-KOON-dah", meaning: "second" },
  { word: "утро", pronunciation: "OO-trah", meaning: "morning" },
  { word: "день", pronunciation: "dyen'", meaning: "day" },
  { word: "вечер", pronunciation: "VYE-cher", meaning: "evening" },
  { word: "ночь", pronunciation: "noch'", meaning: "night" },
  { word: "неделя", pronunciation: "nee-DYEH-lyah", meaning: "week" },
  { word: "месяц", pronunciation: "MYEH-syats", meaning: "month" },
  { word: "год", pronunciation: "goht", meaning: "year" },
  { word: "есть", pronunciation: "yehst'", meaning: "to eat" },
  { word: "пить", pronunciation: "peet'", meaning: "to drink" },
  { word: "спать", pronunciation: "spat'", meaning: "to sleep" },
  { word: "жить", pronunciation: "zhyt'", meaning: "to live" },
  { word: "быть", pronunciation: "byt'", meaning: "to be" },
  { word: "делать", pronunciation: "DYEH-laht'", meaning: "to do / make" },
  { word: "сделать", pronunciation: "SDYEH-laht'", meaning: "to do/make (once, completed)" },
  { word: "хотеть", pronunciation: "kha-TYEHT'", meaning: "to want" },
  { word: "мочь", pronunciation: "moch'", meaning: "to be able to" },
  { word: "можно", pronunciation: "MOHZh-nah", meaning: "it is possible / allowed" },
  { word: "нельзя", pronunciation: "nyel'-ZYAH", meaning: "not allowed / impossible" },
  { word: "любить", pronunciation: "lyoo-BEET'", meaning: "to love" },
  { word: "нравиться", pronunciation: "NRAH-veet'-sah", meaning: "to like (to be pleasing)" },
  { word: "думать", pronunciation: "DOO-maht'", meaning: "to think" },
  { word: "помнить", pronunciation: "POHM-neet'", meaning: "to remember" },
  { word: "забыть", pronunciation: "zah-BYT'", meaning: "to forget" },
  { word: "ждать", pronunciation: "zhdat'", meaning: "to wait" },
  { word: "начать", pronunciation: "nah-CHAT'", meaning: "to start" },
  { word: "закончить", pronunciation: "zah-KON-cheet'", meaning: "to finish" },
  { word: "открыть", pronunciation: "at-KRYT'", meaning: "to open" },
  { word: "закрыть", pronunciation: "zah-KRYT'", meaning: "to close" },
  { word: "войти", pronunciation: "vah-YTEE", meaning: "to enter" },
  { word: "выйти", pronunciation: "VY-tee", meaning: "to exit" },
  { word: "сидеть", pronunciation: "see-DYEHT'", meaning: "to sit" },
  { word: "стоять", pronunciation: "stah-YAT'", meaning: "to stand" },
  { word: "лежать", pronunciation: "lee-ZHAT'", meaning: "to lie (be lying)" },
  { word: "бежать", pronunciation: "beh-ZHAT'", meaning: "to run" },
  { word: "гулять", pronunciation: "goo-LYAT'", meaning: "to walk (for leisure)" },
  { word: "играть", pronunciation: "ee-GRAT'", meaning: "to play" },
  { word: "работать", pronunciation: "rah-BOH-taht'", meaning: "to work" },
  { word: "учиться", pronunciation: "oo-CHEE-tsah", meaning: "to study" },
  { word: "готовить", pronunciation: "gah-TOH-veet'", meaning: "to cook / prepare" },
  { word: "покупать", pronunciation: "pah-koo-PAT'", meaning: "to buy (habitual)" },
  { word: "купить", pronunciation: "koo-PEET'", meaning: "to buy (once)" },
  { word: "большой", pronunciation: "bal'-SHOY", meaning: "big" }
];
